# >---------------------------[ Install Command ]-----------------------------<
#  rails new APP_NAME -m http://railswizard.org/4e5477fc28645502dd5a.rb  -T -J
# >---------------------------------------------------------------------------<
#
#            _____       _ _   __          ___                  _ 
#           |  __ \     (_) |  \ \        / (_)                | |
#           | |__) |__ _ _| |___\ \  /\  / / _ ______ _ _ __ __| |
#           |  _  // _` | | / __|\ \/  \/ / | |_  / _` | '__/ _` |
#           | | \ \ (_| | | \__ \ \  /\  /  | |/ / (_| | | | (_| |
#           |_|  \_\__,_|_|_|___/  \/  \/   |_/___\__,_|_|  \__,_|
#
#   This template was generated by RailsWizard, the amazing and awesome Rails
#     application template builder. Get started at http://railswizard.org
#
#  ___________________________________________________________________________
# |/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/|
# |             |                                                             |
# | Name:       | new_template                                                |
# | URL:        | http://railswizard.org/4e5477fc28645502dd5a.rb              |
# | Updated:    | February 18, 2011 at 18:33PM                                |
# |             |                                                             |
# |\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\|
#  ---------------------------------------------------------------------------

# >----------------------------[ Initial Setup ]------------------------------<

initializer 'generators.rb', <<-RUBY
Rails.application.config.generators do |g|
end
RUBY

template = {"orm"=>"activerecord", "unit_testing"=>"rspec", "integration_testing"=>"steak", "javascript"=>"jquery", "authentication"=>"devise", "templating"=>"haml", "css"=>"sass"}
recipes = template.values.flatten

def say_recipe(name); say "\033[36m" + "recipe".rjust(10) + "\033[0m" + "    Running #{name} recipe..." end
def say_wizard(text); say "\033[36m" + "wizard".rjust(10) + "\033[0m" + "    #{text}" end

@after_blocks = []
def after_bundler(&block); @after_blocks << block; end

# >-----------------------------[ ActiveRecord ]------------------------------<

# Use the default ActiveRecord database store.
say_recipe 'ActiveRecord'

# No additional code required.

# >---------------------------------[ RSpec ]---------------------------------<

# Use RSpec for unit testing for this Rails app.
say_recipe 'RSpec'

gem 'rspec-rails', '>= 2.0.1', :group => [:development, :test]

inject_into_file "config/initializers/generators.rb", :after => "Rails.application.config.generators do |g|\n" do
  "    g.test_framework = :rspec\n"
end

after_bundler do
  generate 'rspec:install'
end

# >---------------------------------[ Steak ]---------------------------------<

# Use Steak and Capybara for integration testing.
say_recipe 'Steak'

gem 'steak', '>= 1.0.0.rc.1'
gem 'capybara'

generate 'steak:install'

# >--------------------------------[ jQuery ]---------------------------------<

# Adds the latest jQuery and Rails UJS helpers for jQuery.
say_recipe 'jQuery'

inside "public/javascripts" do
  get "https://github.com/rails/jquery-ujs/raw/master/src/rails.js", "rails.js"
  get "http://code.jquery.com/jquery-1.5.min.js", "jquery.js"
end

application do
  "\nconfig.action_view.javascript_expansions[:defaults] = %w(jquery rails)\n"
end

gsub_file "config/application.rb", /# JavaScript.*\n/, ""
gsub_file "config/application.rb", /# config\.action_view\.javascript.*\n/, ""

# >--------------------------------[ Devise ]---------------------------------<

# Utilize Devise for authentication, automatically configured for your selected ORM.
say_recipe 'Devise'

gem 'devise'

after_bundler do
  generate 'devise:install'

  case template['orm']
    when 'mongo_mapper'
      gem 'mm-devise'
      gsub_file 'config/intializers/devise.rb', 'devise/orm/active_record', 'devise/orm/mongo_mapper_active_model'
    when 'mongoid'
      gsub_file 'config/intializers/devise.rb', 'devise/orm/active_record', 'devise/orm/mongoid'
    when 'active_record'
      # Nothing to do
      
    generate 'devise user'
  end
end

# >---------------------------------[ HAML ]----------------------------------<

# Utilize HAML for templating.
say_recipe 'HAML'

gem 'haml', '>= 3.0.0'
gem 'haml-rails'

# >---------------------------------[ SASS ]----------------------------------<

# Utilize SASS (through the HAML gem) for really awesome stylesheets!
say_recipe 'SASS'

unless recipes.include? 'haml'
  gem 'haml', '>= 3.0.0'
end


# >-----------------------------[ Custom Code ]-------------------------------<

inside "config/locales" do
  get "https://github.com/ritxi/plantilla_rails/raw/master/i18n/ca.yml", "ca.yml"
  get "https://github.com/ritxi/plantilla_rails/raw/master/i18n/devise.ca.yml", "devise.ca.yml"
end

application do
  "\n    config.i18n.default_locale = :ca\n"
end
gsub_file "config/application.rb", /# config\.i18n\.default_locale = :de\n/, ""

# >-----------------------------[ Run Bundler ]-------------------------------<

say_wizard "Running Bundler install. This will take a while."
run 'bundle install'
say_wizard "Running after Bundler callbacks."
@after_blocks.each{|b| b.call}